//
// Created by Owen Kane on 27/01/2017.
//

#ifndef EXE2_SOFTWARESYSTEMSLABS_AREAOFRECTANGLE_H
#define EXE2_SOFTWARESYSTEMSLABS_AREAOFRECTANGLE_H

int areaOfRectangle(int side1, int side2);

#endif //SOFTWARESYSTEMSLABS_AREAOFRECTANGLE_H
