//
// Created by Owen Kane on 09/02/2017.
//

#ifndef SOFTWARESYSTEMSLABS_NEWMESSAGE_H_H
#define SOFTWARESYSTEMSLABS_NEWMESSAGE_H_H

void  sayHello(char* message);

#endif //SOFTWARESYSTEMSLABS_NEWMESSAGE_H_H